# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Corne-42 Firmeare
  - board: nice_nano_v2
    shield: corne_left
    artifact-name: corne-42-zmk-left
  - board: nice_nano_v2
    shield: corne_right
    artifact-name: corne-42-zmk-right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne-42-settings-reset

  # Lili58 Firmeare
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    artifact-name: lily58-zmk-left
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view
    artifact-name: lily58-zmk-right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: lily58-settings-reset
