# Layout visualization for Keymap Drawer
# You can access this mapping following the link:

layout: { qmk_keyboard: corne_rotated, qmk_layout: LAYOUT_split_3x6_3 }

layers:
  Default:
    # Row 1
    - - $$mdi:keyboard-tab$$
      - { t: Q, h: $$mdi:numeric-3-box-multiple-outline$$, type: held }
      - W
      - E
      - R
      - T
      - Y
      - U
      - I
      - O
      - { t: P, h: $$mdi:numeric-3-box-multiple-outline$$, type: held }
      - "-"

    # Row 2
    - - { t: $$mdi:apple-keyboard-control$$, s: "⌘:`", type: held }
      - A
      - { t: S, h: $$mdi:numeric-1-box-multiple-outline$$, type: held }
      - { t: D, h: $$mdi:numeric-2-box-multiple-outline$$, type: held }
      - { t: F, h: $$mdi:apple-keyboard-shift$$, type: held }
      - G
      - H
      - { t: J, h: $$mdi:apple-keyboard-shift$$, type: held }
      - { t: K, h: $$mdi:numeric-2-box-multiple-outline$$, type: held }
      - { t: L, h: $$mdi:numeric-1-box-multiple-outline$$, type: held }
      - ;
      - { t: "'", h: $$mdi:apple-keyboard-control$$, type: held }

    # Row 3
    - - { t: $$mdi:web$$, s: "⌘:~", h: "2x:⇪", type: held }
      - Z
      - X
      - C
      - V
      - B
      - N
      - M
      - ","
      - .
      - /
      - { t: $$mdi:web$$, h: "2x:⇪", type: held }

    # Thumb Cluster (row 4)
    - - { t: $$mdi:apple-keyboard-option$$, type: held }
      - {
          t: $$mdi:backspace$$,
          s: $$mdi:backspace-reverse$$,
          h: $$mdi:apple-keyboard-command$$,
          type: held,
        }
      - {
          t: $$mdi:keyboard-esc$$,
          h: $$mdi:apple-keyboard-control$$,
          type: held,
        }
      - {
          t: $$mdi:keyboard-return$$,
          h: $$mdi:apple-keyboard-control$$,
          type: held,
        }
      - {
          t: $$mdi:keyboard-space$$,
          h: $$mdi:apple-keyboard-command$$,
          type: held,
        }
      - { t: $$mdi:apple-keyboard-option$$, type: held }

  "Numbers & Navigation (L1)":
    # Row 1
    - ["", 1, 2, 3, 4, 5, ↖, ⇟, ⇞, ↘, "", ""]

    # Row 2
    - - ""
      - 6
      - 7
      - 8
      - { t: 9, h: $$mdi:apple-keyboard-shift$$, type: held }
      - 0
      - ←
      - ↓
      - ↑
      - →
      - ""
      - ""

    # Row 3
    - - { t: $$mdi:web$$, h: "2x:⇪", type: held }
      - ""
      - ""
      - "."
      - ","
      - ""
      - "$$mdi:keyboard-tab-reverse$$"
      - ""
      - ""
      - "$$mdi:keyboard-tab$$"
      - ""
      - { t: $$mdi:web$$, h: "2x:⇪", type: held }

    # Thumb Cluster (row 4)
    - - { t: $$mdi:apple-keyboard-option$$, type: held }
      - {
          t: $$mdi:backspace$$,
          s: $$mdi:backspace-reverse$$,
          h: $$mdi:apple-keyboard-command$$,
          type: held,
        }
      - { t: $$mdi:apple-keyboard-control$$, type: held }
      - { t: $$mdi:apple-keyboard-control$$, type: held }
      - {
          t: $$mdi:keyboard-space$$,
          h: $$mdi:apple-keyboard-command$$,
          type: held,
        }
      - { t: $$mdi:apple-keyboard-option$$, type: held }

  "Symbols (L2)":
    # Row 1
    - ["", "!", "@", "#", $, "%", "[", <, "=", ">", "]", ""]

    # Row 2
    - - ""
      - "'"
      - '"'
      - "^"
      - { t: "/", h: $$mdi:apple-keyboard-shift$$, type: held }
      - \
      - "{"
      - { t: "(", h: $$mdi:apple-keyboard-shift$$, type: held }
      - ":"
      - )
      - "}"
      - ""

    # Row 3
    - - { t: $$mdi:web$$, h: "2x:⇪", type: held }
      - "~"
      - "`"
      - ""
      - "_"
      - ""
      - "|"
      - "&"
      - "*"
      - "+"
      - "-"
      - { t: $$mdi:web$$, h: "2x:⇪", type: held }

    # Thumb Cluster (row 4)
    - - { t: $$mdi:apple-keyboard-option$$, type: held }
      - {
          t: $$mdi:backspace$$,
          s: $$mdi:backspace-reverse$$,
          h: $$mdi:apple-keyboard-command$$,
          type: held,
        }
      - { t: $$mdi:apple-keyboard-control$$, type: held }
      - { t: $$mdi:apple-keyboard-control$$, type: held }
      - {
          t: $$mdi:keyboard-space$$,
          h: $$mdi:apple-keyboard-command$$,
          type: held,
        }
      - { t: $$mdi:apple-keyboard-option$$, type: held }

  "Functions (L3)":
    # Row 1
    - - ""
      - F1
      - F2
      - F3
      - F4
      - F5
      - { t: $$mdi:bluetooth-connect$$, h: 1 }
      - { t: $$mdi:bluetooth-connect$$, h: 2 }
      - { t: $$mdi:bluetooth-connect$$, h: 3 }
      - { t: $$mdi:bluetooth-connect$$, h: 4 }
      - $$mdi:bluetooth-off$$
      - $$mdi:volume-high$$

    # Row 2
    - - ""
      - F6
      - F7
      - F8
      - F9
      - F10
      - $$mdi:skip-backward$$
      - $$mdi:play-pause$$
      - $$mdi:skip-forward$$
      - $$mdi:brightness-5$$
      - $$mdi:brightness-7$$
      - $$mdi:volume-medium$$

    # Row 3
    - - ""
      - F8
      - F9
      - F10
      - F11
      - F12
      - ""
      - ""
      - ""
      - ""
      - ""
      - $$mdi:volume-off$$

    # Thumb Cluster (row 4)
    - - $$mdi:keyboard$$
      - $$mdi:restart$$
      - $$mdi:fit-to-screen-outline$$
      - $$mdi:fit-to-screen-outline$$
      - $$mdi:restart$$
      - $$mdi:keyboard$$

draw_config:
  dark_mode: true
  separate_combo_diagrams: true
  combo_diagrams_scale: 4
  inner_pad_w: 4.0
  inner_pad_h: 4.0
  footer_text: ""
